"""asd

Revision ID: 0ce3b55aff88
Revises: 
Create Date: 2022-11-17 20:30:18.164613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce3b55aff88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('landing', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_id'), 'catalog', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_name'), 'catalog', ['name'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('landing', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_id'), 'subcategory', ['id'], unique=False)
    op.create_index(op.f('ix_subcategory_name'), 'subcategory', ['name'], unique=True)
    op.create_table('subsubcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsubcategory_id'), 'subsubcategory', ['id'], unique=False)
    op.create_index(op.f('ix_subsubcategory_name'), 'subsubcategory', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subsubcategory_name'), table_name='subsubcategory')
    op.drop_index(op.f('ix_subsubcategory_id'), table_name='subsubcategory')
    op.drop_table('subsubcategory')
    op.drop_index(op.f('ix_subcategory_name'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_id'), table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_catalog_name'), table_name='catalog')
    op.drop_index(op.f('ix_catalog_id'), table_name='catalog')
    op.drop_table('catalog')
    # ### end Alembic commands ###
